config/routes.rb
Rails.application.routes.draw do
  root "games#index"
  resources :games, only: %i[index] do
    collection do
      post :reset
      patch :update_board
      post :set_player_names
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
# This class represents the game logic for a Tic Tac Toe game.
# It has a board, a current player, and methods to play a move, check if the game is over, and determine the winner.
# The class is a singleton, meaning there can only be one instance of it in the application.
# The instance method returns the current instance of the game or creates a new one if it doesn't exist.
# The reset method resets the current instance of the game.
# The play method takes a position as an argument and updates the board with the current player's move.
# It also switches the current player and returns a hash with the game state.
# The over? method checks if the game is over by checking if there is a winner or if the board is full.
# The winner method determines the winner by checking the winning combinations on the board.
# The winning_combinations method defines the possible winning combinations in the game.
# The draw? method checks if the game is a draw by checking if the game is over and there is no winner.
# The outcome method returns the outcome of the game based on the winner or draw status.
# The new_game method resets the board and sets the current player to "X".
# The Game class is used in the controller to handle the game logic and update the view based on the game state.
class Game
  attr_accessor :board, :current_player, :player1, :player2, :player1_name, :player2_name
  @@instance = nil

  def self.instance
    return @@instance ||= Game.new
  end

  def set_player_names(player1, player2)
    @player1_name = player1
    @player2_name = player2
  end

  def self.reset
    @@instance.new_game
  end

  def board
    @board
  end

  def current_player
    @current_player
  end

  def current_player_name
    @current_player == "X" ? @player1_name : @player2_name
  end

  def play(position)
    raise "Invalid move" if @board[position] != " "
    @board[position] = @current_player
    switch_players

    return {
      over: over?,
      outcome: outcome,
      current_player: @current_player,
      current_player_name: current_player_name,
      previous_player: previous_player,
      board: @board,
      position: position
    }
  end

  def previous_player
    @current_player == "X" ? "O" : "X"
  end
  def switch_players
    if @current_player == "X"
      @current_player = "O"
    else
      @current_player = "X"
    end
  end

  def over?
    winner.present? || @board.all? { |cell| cell != " " }
  end

  def winner
    winning_combinations.each do |combo|
      if combo.all? { |cell| cell == "X" }
        return @player1_name
      elsif combo.all? { |cell| cell == "O" }
        return @player2_name
      end
    end
    nil
  end

  def winning_combinations
    [
      # rows
      [@board[0], @board[1], @board[2]],
      [@board[3], @board[4], @board[5]],
      [@board[6], @board[7], @board[8]],
      # columns
      [@board[0], @board[3], @board[6]],
      [@board[1], @board[4], @board[7]],
      [@board[2], @board[5], @board[8]],
      # diagonals
      [@board[0], @board[4], @board[8]],
      [@board[2], @board[4], @board[6]]
    ]
  end

  def draw?
    over? && !winner
  end

  def outcome
    return "#{winner} wins!" if winner
    return "It's a draw!" if draw?
    return nil
  end

  def new_game
    @board = Array.new(9, " ")
    @current_player = "X"
  end

  private

  def initialize
    @player1 = "X"
    @player2 = "O"
    @player1_name = "Player 1"
    @player2_name = "Player 2"
    @board = Array.new(9, " ")
    @current_player = @player1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game

  # GET /games or /games.json
  def index
  end

  # POST /games/reset
  def reset
    Game.reset
    render :index
  end

  def set_player_names
    @game.set_player_names(player_names_params[:player1], player_names_params[:player2])
    render :index
  end

  def update_board
    begin
      result = @game.play(params[:position].to_i)
      return render json: result
    rescue StandardError => e
      return render json: { error: e.message }, status: :bad_request
    end
  end

  private

  def player_names_params
    params.permit(:player1, :player2)
  end

  def set_game
    @game = Game.instance
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_game.html.erb
<div>
  <p class="title"><%= @game.player1_name %> (X) vs <%= @game.player2_name %> (O)</p>
  <%= render 'players_form' %>
  <div class="tic-tac-toe-board">
    <% @game.board.each_with_index do |cell, index| %>
      <div class="tic-tac-toe-cell" id=<%= index %>><%= cell %></div>
    <% end %>
  </div>

  <p class="current-player"><%= @game.current_player_name %> turn</p>
  <button id="reset-button">Reset Game</button>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const boardCells = document.querySelectorAll('.tic-tac-toe-cell');

    boardCells.forEach(cell => {
      cell.addEventListener('click', cellClickHandler);
    });

    function cellClickHandler() {
      if (!this.textContent.trim()) {
        const index = this.getAttribute('id');
        updateBoardState(index);
      }
    }

    document.getElementById('reset-button').addEventListener('click', function() {
      fetch('/games/reset', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRF-Token': document.querySelector('[name="csrf-token"]').content,
        },
      })
        .then(response => {
          if (response.ok) {
            location.reload();
          } else {
            alert('Failed to reset the game.');
          }
        });
    });

    function updateBoardState(index) {
      fetch('/games/update_board', {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRF-Token': document.querySelector('[name="csrf-token"]').content,
        },
        body: JSON.stringify({ position: index }),
      })
      .then(response => response.json())
      .then(data => {
        if (!data.error) {
          const cell = document.getElementById(data.position);
          cell.textContent = data.previous_player;
          if (data.over) {
            setTimeout(() => {
              alert(data.outcome);
            }, 100);
            removeEventListeners();
          } else {
            document.querySelector('.current-player').textContent = data.current_player_name + ' turn';
          }
        } else {
          alert(data.error);
        }
      });
    }

    function removeEventListeners() {
      boardCells.forEach(cell => {
        cell.removeEventListener('click', cellClickHandler);
      });
    }
  });
</script>

app/views/games/_players_form.html.erb
<button id="edit-players-button">Edit Players</button>
<div id="modal-players-form">
  <%= form_tag set_player_names_games_url, method: :post do %>
    <label for="player1">Player 1:</label>
    <input type="text" id="player1" name="player1" value="<%= @game.player1_name %>">
    <label for="player2">Player 2:</label>
    <input type="text" id="player2" name="player2" value="<%= @game.player2_name %>">
    <input id="submit-button" class="button" type="submit" value="Submit">
    <button id="cancel-button" class="button">Cancel</button>
  <% end %>
</div>

<script>
  document.getElementById('edit-players-button').addEventListener('click', function() {
    document.getElementById('modal-players-form').style.display = 'block';
  });
  document.getElementById('cancel-button').addEventListener('click', function() {
    closeForm();
  });
  document.getElementById('submit-button').addEventListener('click', function() {
    closeForm();
    window.location.reload();
  });

  window.addEventListener('click', function(event) {
    if (event.target == document.getElementById('modal-players-form')) {
      document.getElementById('modal-players-form').style.display = 'none';
    }
  });

  function closeForm() {
    document.getElementById('modal-players-form').style.display = 'none';
  }
</script>

app/views/games/index.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>

<div id="games">
  <%= render 'game' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicTacToe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>